name: sticky_notes
description: 간단한 노트 애플리케이션
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  sqflite: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
